"""Altera os tipos datetime para date

Revision ID: 1af9520a7ed1
Revises: f3edd45fc237
Create Date: 2023-11-25 19:35:59.543376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1af9520a7ed1'
down_revision: Union[str, None] = 'f3edd45fc237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta_a_pagar_e_receber', 'data_previsao',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('conta_a_pagar_e_receber', 'data_baixa',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conta_a_pagar_e_receber', 'data_baixa',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('conta_a_pagar_e_receber', 'data_previsao',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
