"""Adiciona colunas de controle de baixa de uma conta

Revision ID: 1b7995d6d1fc
Revises: fcebf0dda5cd
Create Date: 2023-11-19 18:16:11.133502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7995d6d1fc'
down_revision: Union[str, None] = 'fcebf0dda5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_a_pagar_e_receber', sa.Column('data_baixa', sa.DateTime(), nullable=True))
    op.add_column('conta_a_pagar_e_receber', sa.Column('valor_baixa', sa.Numeric(), nullable=True))
    op.add_column('conta_a_pagar_e_receber', sa.Column('esta_baixada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_a_pagar_e_receber', 'esta_baixada')
    op.drop_column('conta_a_pagar_e_receber', 'valor_baixa')
    op.drop_column('conta_a_pagar_e_receber', 'data_baixa')
    # ### end Alembic commands ###
