"""Adiciona data previsao em uma conta

Revision ID: f3edd45fc237
Revises: 1b7995d6d1fc
Create Date: 2023-11-20 08:02:59.755457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3edd45fc237'
down_revision: Union[str, None] = '1b7995d6d1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_a_pagar_e_receber', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    op.execute("update conta_a_pagar_e_receber set data_previsao = now()")
    op.alter_column("conta_a_pagar_e_receber", "data_previsao", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_a_pagar_e_receber', 'data_previsao')
    # ### end Alembic commands ###
